# Generated by Django 4.0.4 on 2022-05-24 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=50)),
                ('t_photo', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Ques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('ch1', models.CharField(max_length=50)),
                ('ch2', models.CharField(max_length=50)),
                ('ch3', models.CharField(max_length=50)),
                ('ch4', models.CharField(max_length=50)),
                ('r_ch', models.CharField(max_length=50)),
                ('pub_date', models.DateField(verbose_name='date published')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuizApp.title')),
            ],
        ),
    ]
