# Generated by Django 4.0.4 on 2022-05-25 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='t_photo',
        ),
        migrations.AddField(
            model_name='title',
            name='t_id',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
