# Generated by Django 4.0.4 on 2022-05-27 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0002_remove_title_t_photo_title_t_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='t_img',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
