# Generated by Django 4.0.4 on 2022-05-27 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0003_title_t_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='t_img',
            field=models.ImageField(upload_to='images'),
        ),
    ]
