# Generated by Django 4.0.4 on 2022-05-27 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0004_alter_title_t_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='t_img',
            field=models.CharField(max_length=100),
        ),
    ]
